config/routes.rb
Rails.application.routes.draw do
  resources :product_variants
  resources :products
  root 'products#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :product_variants
    accepts_nested_attributes_for :product_variants
end

app/models/product_variant.rb
class ProductVariant < ApplicationRecord
  belongs_to :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/product_variants_controller.rb
class ProductVariantsController < ApplicationController
  before_action :set_product_variant, only: %i[ show edit update destroy ]

  # GET /product_variants or /product_variants.json
  def index
    @product_variants = ProductVariant.all
  end

  # GET /product_variants/1 or /product_variants/1.json
  def show
  end

  # GET /product_variants/new
  def new
    @product_variant = ProductVariant.new
  end

  # GET /product_variants/1/edit
  def edit
  end

  # POST /product_variants or /product_variants.json
  def create
    @product_variant = ProductVariant.new(product_variant_params)

    respond_to do |format|
      if @product_variant.save
        format.html { redirect_to product_variant_url(@product_variant), notice: "Product variant was successfully created." }
        format.json { render :show, status: :created, location: @product_variant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product_variant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_variants/1 or /product_variants/1.json
  def update
    respond_to do |format|
      if @product_variant.update(product_variant_params)
        format.html { redirect_to product_variant_url(@product_variant), notice: "Product variant was successfully updated." }
        format.json { render :show, status: :ok, location: @product_variant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product_variant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_variants/1 or /product_variants/1.json
  def destroy
    @product_variant.destroy

    respond_to do |format|
      format.html { redirect_to product_variants_url, notice: "Product variant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_variant
      @product_variant = ProductVariant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_variant_params
      params.require(:product_variant).permit(:color, :size, :product_id)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    @product.product_variants.build
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :description, product_variants_attributes: [:id, :color, :size])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def link_to_add_fields(name, f, association)
        ##create a new object from the association(:product_variants)
        new_object = f.object.send(association).klass.new

        ##just create or take the id from the new created object
        id = new_object.object_id
        ##create the fields form
        fields = f.fields_for(association, new_object, child_index: id) do |builder|
            render(association.to_s.singularize + "_fields", f: builder)
    end
    ##pass down the link to the fields form
    link_to(name, '#', class: 'add_fields', data: {id: id, fields: fields.gsub("\n", "")})

  end
end

app/helpers/product_variants_helper.rb
module ProductVariantsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NestedApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/product_variants/_form.html.erb
<%= form_with(model: product_variant) do |form| %>
  <% if product_variant.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product_variant.errors.count, "error") %> prohibited this product_variant from being saved:</h2>

      <ul>
        <% product_variant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :color, style: "display: block" %>
    <%= form.text_field :color %>
  </div>

  <div>
    <%= form.label :size, style: "display: block" %>
    <%= form.text_field :size %>
  </div>

  <div>
    <%= form.label :product_id, style: "display: block" %>
    <%= form.text_field :product_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/product_variants/_product_variant.html.erb
<div id="<%= dom_id product_variant %>">
  <p>
    <strong>Color:</strong>
    <%= product_variant.color %>
  </p>

  <p>
    <strong>Size:</strong>
    <%= product_variant.size %>
  </p>

  <p>
    <strong>Product:</strong>
    <%= product_variant.product_id %>
  </p>

</div>

app/views/product_variants/edit.html.erb
<h1>Editing product variant</h1>

<%= render "form", product_variant: @product_variant %>

<br>

<div>
  <%= link_to "Show this product variant", @product_variant %> |
  <%= link_to "Back to product variants", product_variants_path %>
</div>

app/views/product_variants/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Product variants</h1>

<div id="product_variants">
  <% @product_variants.each do |product_variant| %>
    <%= render product_variant %>
    <p>
      <%= link_to "Show this product variant", product_variant %>
    </p>
  <% end %>
</div>

<%= link_to "New product variant", new_product_variant_path %>

app/views/product_variants/new.html.erb
<h1>New product variant</h1>

<%= render "form", product_variant: @product_variant %>

<br>

<div>
  <%= link_to "Back to product variants", product_variants_path %>
</div>

app/views/product_variants/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product_variant %>

<div>
  <%= link_to "Edit this product variant", edit_product_variant_path(@product_variant) %> |
  <%= link_to "Back to product variants", product_variants_path %>

  <%= button_to "Destroy this product variant", @product_variant, method: :delete %>
</div>

app/views/products/_form.html.erb
<%= form_for @product do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
   <%= form.fields_for :product_variants do |f| %>
    <%= render 'product_variant_fields', f: f %>

    <% end %>

    <%= link_to_add_fields "Add Variant", form, :product_variants %>


  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>

$('form').on('click', 'remove-fields', function(event) {
  console.log('removed')
    $(this).prev('input[type=hidden]').val('1');
    $(this).closest('fieldset').hide();
    return event.preventDefault();
  });

$('form').on('click', '.add_fields', function(event) {
    console.log('add!')
     var regexp, time;
     time = new Date().getTime();
     
     regexp = new RegExp($(this).data('id'), 'g');
     $(this).before($(this).data('fields').replace(regexp, time));
     return event.preventDefault();
    });

</script>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Title:</strong>
    <%= product.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

</div>

app/views/products/_product_variant_fields.html.erb


<%= f.label :color %><br>
    <%= f.text_field :color %><br>

    <%= f.label :size %><br>
   <%= f.text_field :size %>
   <%= f.hidden_field :_destroy %>
   <%= link_to "Remove", "#", id:'remove_fields', class: 'remove_fields'%><br>


    

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Products</h1>

<div id="products">
  <% @products.each do |product| %>
    <%= render product %>
    <p>
      <%= link_to "Show this product", product %>
    </p>
  <% end %>
</div>

<%= link_to "New product", new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<p>
  <strong>Available Variants: <%= @product.product_variants.count %></strong>
  
</p>

<% @product.product_variants.each do |variant|%>

<p>

  <%= variant.color %>
  <%= variant.size %>
</p>

<% end %>

<div>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>

  <%= button_to "Destroy this product", @product, method: :delete %>
</div>